### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Romz24** [FloweyTheFlower420/rebark-fabric#1]
When I install your mod and try to start the server it crashes.

[crash-2022-05-18_11.59.32-server.txt](https://github.com/FloweyTheFlower420/rebark-fabric/files/8714774/crash-2022-05-18_11.59.32-server.txt)

**Comment by Floweynt** [comment]
Pretty sure I patched this in this jar, please test it for me.
https://file.io/t2PeeT8X12ZY

**Comment by Romz24** [comment]
This problem still remains

[crash-2022-05-19_03.05.24-server.txt](https://github.com/FloweyTheFlower420/rebark-fabric/files/8721623/crash-2022-05-19_03.05.24-server.txt)

**Comment by Floweynt** [comment]
https://file.io/J8MC6ql2TCpI
Give the full logs with this version. I believe this is a mod compat issue.

**Comment by Romz24** [comment]
Sorry for the delay in reply. I checked, it still crashes. Here are the server logs and the crash log.

[crash.zip](https://github.com/FloweyTheFlower420/rebark-fabric/files/8748138/crash.zip)
